all: name email github

name:
	@read -p 'What is your name? ' name; echo "$$name" > $@

email:
	@read -p 'What is your email address? ' email; echo "$$email" > $@

github:
	@read -p 'What is your GitHub username? ' github; echo "$$github" > $@
